### ISSUE TITLE
Wrappers

### ISSUE THREAD

**Issue by jazzbre** [Jonathan-Racaud/awesome-beef#23]
Hi you might also want to add these cross-platform wrappers (Windows, macOS, Linux, Android/iOS in the works) :

https://github.com/jazzbre/sdl2-beef
https://github.com/jazzbre/bgfx-beef
https://github.com/jazzbre/imguibgfx-beef
https://github.com/jazzbre/Chipmunk2D-beef
https://github.com/jazzbre/box2d-beef
https://github.com/jazzbre/soloud-beef
https://github.com/jazzbre/minicoro-beef
https://github.com/jazzbre/nativefiledialog-beef

Cheers,
A

**Comment by Jonathan-Racaud** [comment]
Hi !

Thanks for the suggestion, I've added most of them. I would need more information about those projects before adding them or not as they collide with existing one. I'd like to find a way to list them without it being to confusing.

- SDL2-beef: Compared to the one included with Beef.
- bgfx-beef: Compared to the official bgfx beef binding (already listed in the list)

**Comment by jazzbre** [comment]
Hey,
the SDL2-beef is basically the same wrapper (I sync it from beeflang), but has the whole build system and it's cross-platform.
Bgfx-beef is basically the official bgfx beef binding (I've added it to bgfx) but also beef projects and examples.

Thanks!

**Comment by Jonathan-Racaud** [comment]
Thanks for the precision, I've added them as well.
