### ISSUE TITLE
Remove Vulkan-bf because it is a dead link

### ISSUE THREAD

**Issue by DerTee** [Jonathan-Racaud/awesome-beef#31]
Under "Game Development" > "Libraries" > "Vulkan-bf" with link https://github.com/ExoKomodo/Vulkan-bf you get a HTTP 404

Looks like the original author Exokomodo deleted the repo, I could not find anything related to beef and vulkan in his public repos.

**Comment by Jonathan-Racaud** [comment]
Thanks for the notice. I removed the link.
