### ISSUE TITLE
Linux binaries

### ISSUE THREAD

**Issue by Booklordofthedings** [Jonathan-Racaud/awesome-beef#48]
Im making this an issue instead of a pr since idk if or how we could add it to the repo, but I provide a linux binary for apt on the website: [Beefinstall.com](https://beefinstall.com/).
And I thought that this might be a nice addition here

**Comment by Jonathan-Racaud** [comment]
Yeah I saw the discussion on the discord about this. I've added an **Tools - Installer** section with the link to your website.
I don't know if it's the best way to represent the project, but at least it is linked at the top which should make it easily discoverable for people coming to this repo.
